name: CODE Validator

on:
  push:
    tags: 
      - java_submitted
      - java_tac_submitted 
      - mips_submitted


jobs:
  validate_submission:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # fetch-depth is set to zero to obtain everything ... which includes history, logs., refs

    - name: Validate Coding Assignment
      run: make validate

